name: Dagger
on:
  push:
    branches: [main]

jobs:
  hello:
    name: CUDA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build CUDA Image
        run: go run -v dagger/main.go
